steps:
# https://cloud.google.com/cloud-build/docs/kaniko-cache#kaniko-build
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - '--destination=eu.gcr.io/${PROJECT_ID}/${_NAME}:latest'
  - '--destination=eu.gcr.io/${PROJECT_ID}/${_NAME}:${COMMIT_SHA}'
  - '--cache=true'
  - '--cache-ttl=744h'

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_NAME}'
  - '--image=eu.gcr.io/${PROJECT_ID}/${_NAME}:${COMMIT_SHA}'
  - '--platform=managed'
  - '--port=8080'
  - '--region=${_REGION}'
  - '--allow-unauthenticated'
