steps:
- name: 'gcr.io/cloud-builders/gcloud-slim'
  args:
  - functions
  - deploy
  - ${_NAME}
  - --region=${_REGION}
  - --trigger-http
  - --allow-unauthenticated
  - --source=.
  - --entry-point=main
  - --runtime=nodejs12
  - --memory=128MB
  - --update-env-vars=APP_ENV=serverless,VERSION_BUILD=${SHORT_SHA}
